# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ancla < Formula
  desc "CLI client for the Ancla deployment platform"
  homepage "https://ancla.dev"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.1.1/ancla_1.1.1_darwin_amd64.tar.gz"
      sha256 "e800596a8c6dbee81c40fb1480912abe3e790afef896c20dd9d6dc909cbb2fcb"

      define_method(:install) do
        bin.install "ancla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.1.1/ancla_1.1.1_darwin_arm64.tar.gz"
      sha256 "b0921b056f6457096f478d8b32cae0d71573687946736495635250f013aaba8f"

      define_method(:install) do
        bin.install "ancla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.1.1/ancla_1.1.1_linux_amd64.tar.gz"
      sha256 "748963ed22c163d9b3e3e6e026466d8c5c5b72a2b2f334a04d61666dbe3263a1"
      define_method(:install) do
        bin.install "ancla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.1.1/ancla_1.1.1_linux_arm64.tar.gz"
      sha256 "e5f33dd2a057468df909c518a65c29c8d1f2ee5467534500fa75d5d2a328f5a2"
      define_method(:install) do
        bin.install "ancla"
      end
    end
  end

  def caveats
    <<~EOS
      To update: brew upgrade ancla
    EOS
  end

  test do
    system "#{bin}/ancla", "version"
  end
end
